version: "3.8"

services:
  proxy:
    image: classroom-conversation/nginx:prod
    build:
      context: ./nginx
      target: production
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
    volumes:
      - static_vol:/www/staticfiles

  backend:
    image: classroom-conversation/backend:prod
    build:
      context: ./backend
      target: production
    container_name: backend
    restart: always
    env_file:
      - backend.env
      - db.env
    depends_on:
      - db
    links:
      - db
    volumes:
      - static_vol:/app/staticfiles
      - media_vol:/app/mediafiles

  frontend:
    image: classroom-conversation/frontend:prod
    build:
      context: ./frontend
      target: production
    container_name: frontend
    restart: always
    depends_on:
      - backend

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=db
volumes:
  db_vol:
  static_vol:
  media_vol:
