# Generated by Django 4.0.3 on 2022-12-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_illustration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=48, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('selectable', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='avatars/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
